name: Alerta de Planilha Diário

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  executar_alerta:
    runs-on: ubuntu-latest
    
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar bibliotecas necessárias
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Executar script de verificação
        env:
          GOOGLE_CRED_JSON: ${{ secrets.GOOGLE_CRED_JSON }}
          NUMEROS_WHATSAPP: ${{ secrets.NUMEROS_WHATSAPP }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          NOME_ABA: ${{ secrets.NOME_ABA }}
        run: python main.py